font_family      JetBrainsMono Nerd Font
font_size        11.0

window_padding_width 12
confirm_os_window_close 0

cursor           #c8c093
cursor_text_color #181616
cursor_shape     block
cursor_blink_interval 0

shell /usr/bin/zsh -c "tmux new-session -A -s unc"

scrollback_lines 10000

mouse_hide_wait 3.0

copy_on_select          clipboard
clipboard_control       write-clipboard write-primary read-clipboard read-primary

include kanagawa-dragon.conf

map ctrl+backspace send_text all \x17
