# Force Zsh
shell /usr/bin/zsh
include dank-theme.conf
# --- Layout & Font ---
window_padding_width 12
confirm_os_window_close 0
font_family      JetBrainsMono Nerd Font
font_size        10.0

# Ctrl+Backspace → delete word backward
map ctrl+backspace send_text all \x17
