
### Startup applications
#exec dms run
exec quickshell -c pill
exec_always wl-paste --watch cliphist store
exec vicinae server
exec awww-daemon
#exec_always swaybg -i ~/Pictures/Wallpapers/wallhaven-yqgwpg.png -m fit
exec phylax
exec bash -l /home/unc/.config/scripts/activity-tracker.sh

exec syncthing --no-browser
# Import environment for systemd/dbus
exec dbus-update-activation-environment --all
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Force the desktop ID to 'sway' so portals recognize it
exec hash dbus-update-activation-environment 2>/dev/null && \
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec systemctl --user start graphical-session.target
