
### Windows defaults
default_border pixel
gaps inner 1
gaps outer 0

# class                 border  backgr. text    indicator child_border
client.focused          #b0b0b0 #222222 #ffffff #b0b0b0   #b0b0b0
client.focused_inactive #444444 #222222 #b0b0b0 #444444   #444444
client.unfocused        #222222 #111111 #888888 #222222   #222222

# titlebar_border_radius 8
default_decoration border_radius 0 shadow false shadow_dynamic false shadow_size 40 shadow_blur 30 shadow_offset 40 40 shadow_color #00000070 dim false dim_color #00000040


# Idle inhibit for fullscreen windows
for_window [all] inhibit_idle fullscreen

# Layout settings
layout_default_width 0.5
layout_default_height 1.0
layout_widths [0.33333333 0.5 0.666666667 1.0]
layout_heights [0.33333333 0.5 0.666666667 1.0]

# These are the default values for some useful scroll options, consult
# `man 5 scroll` and change them to your preference

# align_reset_auto yes
# cursor_shake_magnify false
# cycle_size_wrap false
 fullscreen_movefocus true nofollow
# fullscreen_on_request default
 maximize_if_single true
# workspace_next_on_output_create_empty true
# xwayland_output_scale true
# focus_wrapping no
#focus_on_window_activation focus
# xdg_activation_force false

# Options: yes | no | always
focus_follows_mouse no

# Animations

animations {
    enabled yes 
    # Global default: Faster 100ms, clean ease-out for awareness
    default yes 50 var 3 [ 0 0 0.2 1 ]

    # Open: Linear is fastest to render, 100ms is a quick pop
    window_open yes 50 var 3 [ 0 0 1 1 ]

    # Move: 120ms gives your brain just enough time to see the slide
    window_move yes 80 var 3 [ 0 0 0.2 1 ]

    # Size: Fast 100ms to keep the UI responsive while resizing
    window_size yes 50 var 3 [ 0 0 0.2 1 ]

    overview no
    jump no
}
