#
# Workspace rules:
#
# Opens a terminal when creating workspace 6
# workspace 6 exec kitty


#WORKSPACE RULES (BWAHAHAHHA)
for_window [title="^Picture-in-Picture$"] floating enable, sticky enable, border none, resize set 400 225, move position 100 ppt 0, move left 410
for_window [title="Picture in Picture"] floating enable, sticky enable, border none, resize set 400 225, move position 100 ppt 0, move left 410 
for_window [title="Picture in picture"] floating enable, sticky enable, border none, resize set 400 225, move position 100 ppt 0, move left 410
for_window [title="mpv"] floating enable, sticky enable resize set 400 225, move position 100 ppt 0, move left 410
no_focus [title="Picture in Picture"]
no_focus [title="Picture in picture"]
for_window [title="discord.com is sharing a window.*"] border none
# Float the focused window, make it sticky, remove border, and resize it
bindsym $mod+Shift+p floating enable, sticky enable, resize set 400 225, move position 100 ppt 0, move left 410
# Assign apps to specific workspaces
## --- WORKSPACE RULES (BWAHAHAHHA) ---

# 1. THE ASSIGNMENTS (Puts the app in the right place silently before it draws)
assign [app_id="firefox"]           workspace number 1
assign [app_id="kitty"]             workspace number 2
assign [app_id="obsidian"]          workspace number 3
assign [app_id="vesktop"]           workspace number 5
assign [app_id="telegram-desktop"]  workspace number 5
assign [app_id="whatsapp"]          workspace number 5

assign [app_id="com.obsproject.Studio"] workspace number 7
assign [app_id="veadotube-mini"]        workspace number 7
assign [app_id="showmethekey-gui"]      workspace number 7


# 2. THE JUMPS (Tells your screen to follow the app to its assigned workspace)
for_window [app_id="firefox"]           workspace number 1
for_window [app_id="kitty"]             workspace number 2
for_window [app_id="obsidian"]          workspace number 3
#for_window [app_id="vesktop"]           workspace number 5
for_window [app_id="telegram-desktop"]  workspace number 5
for_window [app_id="whatsapp"]          workspace number 5

for_window [app_id="com.obsproject.Studio"] workspace number 7
for_window [app_id="veadotube-mini"]        workspace number 7
for_window [app_id="showmethekey-gui"]      workspace number 7


# 3. FLOATING / OVERLAY RULES
# The "Keystroke Overlay" (The thingy)
# Stays floating, sticky, and ignores focus wrapping so it doesn't interrupt coding
for_window [app_id="one.alynx.showmethekey"] floating enable, sticky enable, border none, focus_wrapping no
# include @sysconfdir@/scroll/config.d/*
#bindsym $mod+ctrl+t exec ~/.config/scripts/scroll-quick-tile.sh
